version: "3.2"
services:
  auth:
    build: ./auth
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    ports:
        - 1337:1337
    #   - 5000:5000
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'auth'
      MYSQL_PASSWORD: 'authpass'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always

